# fly.toml app configuration file generated for driftapp-backend-igor-dev-late-hill-6194 on 2024-09-25T17:22:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'driftapp-backend-igor-dev-late-hill-6194'
primary_region = 'lhr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile_drift'

[env]
  DIGGER_HOSTNAME = 'https://driftapp-backend.digger.dev'

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
